### ISSUE TITLE
Bug Report: Character Haxeflixel Scary Jumpscare

### ISSUE THREAD

**Issue by B01Coding** [YoshiCrafter29/YoshiCrafterEngine#104]
Scary!

Yes is modded

## Which target are you using?
- [x] Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.7.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
create char and the scary!
## Please describe your issue. Provide extensive detail and images if possible.
Characters being Haxelflixel

**Comment by YoshiCrafter29** [comment]
Weird. Are you sure you're **really** using the latest version? Cause as far as i tried, this bug does not occur, even on the new assets system.

**Comment by B01Coding** [comment]
yse

**Comment by B01Coding** [comment]
![image](https://user-images.githubusercontent.com/92312822/159366334-37bd6a0a-f7c4-47d2-86f1-e16320fb81ec.png)

**Comment by YoshiCrafter29** [comment]
Seems like an XML issue. Make sure it's exported using Sparrow v2. Closing the issue due to inactivity.
