### ISSUE TITLE
Enhancement: opponent play

### ISSUE THREAD

**Issue by dimuzicle** [YoshiCrafter29/YoshiCrafterEngine#112]
that you can play as opponent

**Comment by YoshiCrafter29** [comment]
Pros: haha i can play as kb in termination and kill the shit out of bf
Cons: problems with health, some mods won't set events for onDadHit for evil notes for example, and it will complicate mods.

You still can make your own script do this, but i dont think it'll be added in the engine, or at least for each mods.
