### ISSUE TITLE
Bug Report: File Dialogues don't work on MacOS

### ISSUE THREAD

**Issue by prokube** [YoshiCrafter29/YoshiCrafterEngine#134]
---
## Which target are you using?
take a fat guess

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.7.0 Release (self-compiled source code)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Just go into the toolbox and try to select the inst / voices for a new song. or do anything with a file dialog really

## Please describe your issue. Provide extensive detail and images if possible.
Clicking on any button that opens a file dialogue will cancel the dialog. Looking at the Terminal traces, when I click on the button it says:
```
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `osascript  -e 'try' -e 'POSIX path of ( choose file with prompt "Choose your song's instrumental (.ogg)" )' -e 'on error number -128' -e 'end try''
```

Haven't done much testing, haven't looked at VSC debugging to see what it says. It's likely an issue with Lime, or probably the params the code passes in `CoolUtil.OpenDialogue`. 😐 
---

**Comment by YoshiCrafter29** [comment]
It's more likely to be an issue with Lime. You should make an issue on the lime repo, since i'm using their `lime.ui.FileDialog` class.
![image](https://user-images.githubusercontent.com/81191621/161914147-176611f1-b5e5-4942-87ec-1860da94007b.png)
