### ISSUE TITLE
Bug Report: [when i pressed enter to test my chart this happened]

### ISSUE THREAD

**Issue by goldallan11** [YoshiCrafter29/YoshiCrafterEngine#137]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
YoshiCrafter Engine v1.7.3 - FNF v0.2.7.1

## Please describe your issue. Provide extensive detail and images if possible.
i was making a chart then i pressed enter to test it and this appeared:
---
![error](https://user-images.githubusercontent.com/101950719/161293739-342e4339-fe02-43d0-897d-3875501735f4.png)

**Comment by YoshiCrafter29** [comment]
Fixed
