### ISSUE TITLE
Bug Report: Characters with miss animations miss before singing

### ISSUE THREAD

**Issue by AnonymousUser351** [YoshiCrafter29/YoshiCrafterEngine#138]
## Which target are you using?
Windows
## What version of the engine are you using (Bottom left of the screen in main menu) ?
v1.7.3
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
import any character with miss animations and add a singing animation
## Please describe your issue. Provide extensive detail and images if possible.
self-explanatory
---

**Comment by YoshiCrafter29** [comment]
Fixed
