### ISSUE TITLE
Enhancement: Song Editor

### ISSUE THREAD

**Issue by Piratefoxy216** [YoshiCrafter29/YoshiCrafterEngine#142]
be able to change stage in the song editor cuz it would be less painful and easier...

**Comment by YoshiCrafter29** [comment]
Do you mean Chart Editor?

It's implemented in chart jsons in the dev channel, and a script editor per chart will be added in the Chart Editor (so that you can add stuff such as stages)

**Comment by Piratefoxy216** [comment]
I find it kinda there can be a easier way, but the other also works and
isn't that hard so idk.
