### ISSUE TITLE
When i try to access the chart editor this appears.

### ISSUE THREAD

**Issue by S4mueldaCosta** [YoshiCrafter29/YoshiCrafterEngine#147]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.7.3
## Please describe your issue. Provide extensive detail and images if possible.
---
![7591072b8fffd8e05f09ee54faf0d6fa](https://user-images.githubusercontent.com/99627176/162554893-d559488b-1319-4ee8-bd83-29cde0bc722a.png)

**Comment by YoshiCrafter29** [comment]
Fixed
