### ISSUE TITLE
Bug Report: New Charter Crashes Game

### ISSUE THREAD

**Issue by blissedandpissed** [YoshiCrafter29/YoshiCrafterEngine#150]
## Which target are you using?
- [*] Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
This version, v1.7.3 dev: https://github.com/YoshiCrafter29/YoshiCrafterEngine/actions/runs/2116067460 but still isn't fixed on newer builds

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Create a new mod, add a song, access that song in freeplay or story mode and press 7 to access new chart editor.
## Please describe your issue. Provide extensive detail and images if possible.
If pressing 7 to access the new chart editor on any song other than the base game it will cause the engine to crash.
![a](https://user-images.githubusercontent.com/101831482/163016678-f14a279c-2811-420b-8e0e-17cc8b58bef8.PNG)

**Comment by YoshiCrafter29** [comment]
Already fixed in latest build
