### ISSUE TITLE
Bug Report: [Stage editor moving the camera and characters to a different location.]

### ISSUE THREAD

**Issue by bruh1cat** [YoshiCrafter29/YoshiCrafterEngine#151]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.7.3
## Please describe your issue. Provide extensive detail and images if possible.
--- Stage editor moving the camera and characters to a different location.

**Comment by YoshiCrafter29** [comment]
Any steps to reproduce the bug? Also, if your camera is too far away, you can use Ctrl+Backspace to reset it.

**Comment by bruh1cat** [comment]
> Any steps to reproduce the bug? Also, if your camera is too far away, you can use Ctrl+Backspace to reset it.

Sorry for the late response I'll send you a vid

**Comment by bruh1cat** [comment]
Here's the video:

https://user-images.githubusercontent.com/98327930/163866855-b8e536f7-dd5f-4f0b-9df6-453eb564ef9f.mp4

**Comment by bruh1cat** [comment]
> Here's the video:
> 
>  2022-04-18.15-43-24.mp4

Even if I edit it again it still doesn't fix it.

**Comment by YoshiCrafter29** [comment]
Mind if you send over the stage json and the sprites with it? Seems to be an issue with updateHitbox.

**Comment by bruh1cat** [comment]
[s.zip](https://github.com/YoshiCrafter29/YoshiCrafterEngine/files/8508086/s.zip)

**Comment by YoshiCrafter29** [comment]
Thanks. I'll look into the issue.

**Comment by AwesomezPro99** [comment]
1.7.0. I used it, copy and pasted the json file to the latest version and it worked.

**Comment by YoshiCrafter29** [comment]
Fixed
