### ISSUE TITLE
Bug Report: Can't Update Yoshi Engine Version Even Though It IS The Latest Version

### ISSUE THREAD

**Issue by AdeebHendri** [YoshiCrafter29/YoshiCrafterEngine#152]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
v1.7.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
no images :/

## Please describe your issue. Provide extensive detail and images if possible.
I can't Update to the LATEST Version of Yoshi Engine, Even Though v1.7.3 IS the latest version of Yoshi Engine, That Version Is NOT Found on Yoshi Engine Github. that's all i know.
---

**Comment by YoshiCrafter29** [comment]
Updated the engine, now its really the latest version
