### ISSUE TITLE
Enhancement: Achievements

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#160]
Why don't you do Achievements (with custom Avievements supporting (maybe))? (like in Psych Engine)

**Comment by blissedandpissed** [comment]
yeah and call it medals ( cuz thats what achievements are called in newgrounds )

**Comment by YoshiCrafter29** [comment]
Planned

**Comment by FirePrinceITA** [comment]
+ you can connect these achievements to gamejolt achievements, there are alot of tutorials on how to do that on yt

**Comment by te-agma-at** [comment]
here's a template for a medal icon if anyone wants it (and icon for the Friday Night Funker medal)
![medal-template](https://user-images.githubusercontent.com/72958435/168919799-b98c1002-39bd-4dac-b36a-186dd31f466c.png)
![medal-funker](https://user-images.githubusercontent.com/72958435/168919812-33d53b5f-4c5b-4ca3-abd0-3fa3d4e57d51.png)

**Comment by YoshiCrafter29** [comment]
Done
