### ISSUE TITLE
Enhancement: Camera speed

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#162]
why don't add camera speed option to stage editor? (like in Psych Engine stage's .json's)

**Comment by YoshiCrafter29** [comment]
Like follow lerp?

```haxe
function musicstart() {
     PlayState.camFollowLerp = whateverValueYouWant;
}
```

**Comment by YoshiCrafter29** [comment]
Will check btw to add this in the stage editor

**Comment by YoshiCrafter29** [comment]
![image](https://user-images.githubusercontent.com/81191621/164706084-d7225f7f-1df9-40eb-8410-e48cc326959a.png)

**Comment by chillultimated** [comment]
> ![image](https://user-images.githubusercontent.com/81191621/164706084-d7225f7f-1df9-40eb-8410-e48cc326959a.png)

yea, I actually meant this.
