### ISSUE TITLE
Bug Report: Blammed Note visibility

### ISSUE THREAD

**Issue by PhxR3d** [YoshiCrafter29/YoshiCrafterEngine#163]
## Which target are you using?
Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.8.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
All you have to do is play blammed and get to the cool epic section where the skins change.

## Please describe your issue. Provide extensive detail and images if possible.
The notes for the part in blammed where the skins change (dk what else to call it ;-;) are less visible than they're supposed to be.
![Screenshot 2022-04-21 215544](https://user-images.githubusercontent.com/83072269/164589212-0c8e376d-2dd0-40d7-a1ca-6fe158d52a32.png)

**Comment by YoshiCrafter29** [comment]
![image](https://user-images.githubusercontent.com/81191621/164703230-81d08e7a-0835-48ef-957a-628a830a6eca.png)
Fixed
