### ISSUE TITLE
Enhancement: Shaders

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#164]
[First, I see something about shaders in Stage editor and thats maybe my bad that I dont know how to use it but whatever]

Shaders support like in Psych Engine. Maybe add possibility in chart editor to select shaders for song or ikd xd. Something like in Cuphead week in Indie Cross mod

**Comment by YoshiCrafter29** [comment]
It's already in the engine

Check the `shader` folder and the Blammed modchart for examples.
