### ISSUE TITLE
Enhancement: Easly Custom Game Over Screen

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#165]
[First I (maybe) know how to add custom game over's but you can make it more easy for noobs in YoshiCrafterEngine]

It will be in the Toolbox. Like Character editor but with custom deatch. Also adding custom game over sound [like in vs Impostor Defeat week] and custom game over music

(I know I'm not explaining well)

**Comment by BernardoGP4504** [comment]
there's a way to change the gameover bf (you may have mention it already)

**Comment by YoshiCrafter29** [comment]
![image](https://user-images.githubusercontent.com/81191621/168554615-85103982-291c-4b38-90dd-7e57041d8402.png)
You can alter these static values using GameOverSubstate.value (no need to reset them at the end of the song, they're reset automatically)
