### ISSUE TITLE
Enhancement: Custom Health bars

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#166]
[custom health bars maybe allready in engine and its my bad that idk how to use it, but like if its in engine you can make this easier]
adding new feature in the Toolbox "health bars" where you can create custom health bar (like in Indie Cross) 
the options of this will be something like: icons position, health bar image, image position, icons will be behind health bar or in front.

**Comment by funnyacc** [comment]
make a new file in ui called FlxBar.hx

**Comment by BernardoGP4504** [comment]
there is kinda of a way just replace the healthbar (`assets\shared\images\healthBar.png`) with your custom one (the part where the colors of the characters in the healthbar needs to be transparent to work). But that is going to change the healthbar for all songs

**Comment by YoshiCrafter29** [comment]
`PlayState.healthBarBG.loadGraphic(Paths.image('your-healthbar'));`
