### ISSUE TITLE
Bug Report: Black Chart Grid

### ISSUE THREAD

**Issue by 0-skid** [YoshiCrafter29/YoshiCrafterEngine#168]
## Which target are you using?
- [ x ] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
v1.8.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
no

## Please describe your issue. Provide extensive detail and images if possible.
the chart editor grid doesn't show, but instead is black (i'm not sure if this is because of the PS at the top or not)
![unknown](https://user-images.githubusercontent.com/85322671/164985794-06648fc6-67d0-43a2-a01e-d8be11793cfb.png)

**Comment by YoshiCrafter29** [comment]
Seems like a memory issue. Are you sure the system have enough free memory?

**Comment by 0-skid** [comment]
> Seems like a memory issue. Are you sure the system have enough free memory?

pretty sure you're right, with the engine open i'm using 67% memory

**Comment by YoshiCrafter29** [comment]
closed due to inactivity
