### ISSUE TITLE
Bug Report: Offset doesnt apply in chart editor

### ISSUE THREAD

**Issue by Spronsy** [YoshiCrafter29/YoshiCrafterEngine#169]
I was having a bit of frustration trying to get my offset to be just right and noticed the new chart editor and its playback speed feature.
I figured this would make it alot easier to see if my offset was right by using note click with a slow playback speed, but i noticed no matter what absurd number i set my offset to it was always off sync by the same amount.

I don't know if this is exclusively an issue with the playback or just an issue with the charter in general.

**Comment by YoshiCrafter29** [comment]
Offset is now supported in chart editor.
