### ISSUE TITLE
Bug Report: Null Object Reference while starting custom week from Story Mode

### ISSUE THREAD

**Issue by BernardoGP4504** [YoshiCrafter29/YoshiCrafterEngine#170]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
Well, i am using the most recent version (1.8.1)
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
well what i did was that ive changed some files trying to get a noteskin to work (because i didn't knew the skins folder) in `assets/shared/images`
## Please describe your issue. Provide extensive detail and images if possible.
When i started my week from the Story Mode an error popped up and the game's screen was totally black.
![imagem_2022-04-28_165852588](https://user-images.githubusercontent.com/101405920/165835489-6050cebd-17db-4f6c-a199-847a87dc183e.png)

---

**Comment by BernardoGP4504** [comment]
by pressing `OK` i get a smaller error box saying Null Object Reference and if you press `OK` the engine crashes

**Comment by YoshiCrafter29** [comment]
missing animations in note skin, which causes the engine to crash

its a problem with your file, closing this thread
