### ISSUE TITLE
Bug Report: Character Camera offset is off

### ISSUE THREAD

**Issue by cherryiguess** [YoshiCrafter29/YoshiCrafterEngine#177]
While I was messing around, I noticed that the camera is off during gameplay when focusing on Boyfriend, this is the camera offset in the editor  (-310 for X, no offset for Y, also uses Character.hx, the character is also scaled to 6, incase thats the problem or something)
![image](https://user-images.githubusercontent.com/93490646/166831679-77024c0a-bdc4-4c10-8e93-fcf240083d5f.png)
It looks like this during gameplay
![image](https://user-images.githubusercontent.com/93490646/166831857-d952501d-d7ae-46a5-8c3b-37037d51ebf4.png)
I'm using Windows, and the Version is 1.8.1, This could be a me problem but I'm not sure

**Comment by YoshiCrafter29** [comment]
bob the builder bob the builder can we fix it

**Comment by YoshiCrafter29** [comment]
bob the builder yes we can
