### ISSUE TITLE
Help: How do you add indices to a character?

### ISSUE THREAD

**Issue by LeonGamerPS4** [YoshiCrafter29/YoshiCrafterEngine#178]
#### Please note that the documentation is still under construction.
i'm trying to make a custom gf character for my mod, but i cannot add any indices to the characters. how can i add them?

**Comment by cherryiguess** [comment]
for now just use Character.hx for gf characters, the editor doesn't support indiced animations (if im correct)

**Comment by YoshiCrafter29** [comment]
> for now just use Character.hx for gf characters, the editor doesn't support indiced animations (if im correct)

JSON supports it, but char editor doesnt show the option.
Will be added in the next update.

**Comment by LeonGamerPS4** [comment]
> 

ok
