### ISSUE TITLE
Bug Report: Duet Camera Not Working

### ISSUE THREAD

**Issue by PhxR3d** [YoshiCrafter29/YoshiCrafterEngine#180]
## Which target are you using?
Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Opening the charter and trying to use the duet camera slider on a section that wasn't section 0.

## Please describe your issue. Provide extensive detail and images if possible.
When trying to use the duet slider on a section that isn't Section 0, it doesn't move for some reason.

**Comment by YoshiCrafter29** [comment]
Are you sure you checked the "Duet Camera" checkbox?

**Comment by PhxR3d** [comment]
Yes.

**Comment by YoshiCrafter29** [comment]
Are you sure the slider isn't at the border left or border right?
The slider being all the way to the left is basically the same as the opponent's camera for example

**Comment by PhxR3d** [comment]
I couldn't even move it.

**Comment by PhxR3d** [comment]
Even if I tried to move it- unless it was section 0 it wouldn't move.

**Comment by YoshiCrafter29** [comment]
Mind if you send over the chart?

**Comment by PhxR3d** [comment]
It would happen regardless of chart. I made sure to check. Here's a video showing what I mean. It's a yt link cuz the file was too big.
https://youtu.be/sdqHQM47wPQ

**Comment by BernardoGP4504** [comment]
im also having this

**Comment by BernardoGP4504** [comment]
But how did you fix it?!??

Em seg, 16 de mai de 2022 14:12, YoshiCrafter29 ***@***.***>
escreveu:
