### ISSUE TITLE
Help: modcharts

### ISSUE THREAD

**Issue by Tavish-153** [YoshiCrafter29/YoshiCrafterEngine#184]
#### Please note that the documentation is still under construction.

I want to know how to do modcharts via lua or hx just tell me the strum names I'll do it by my self or leave some code

**Comment by YoshiCrafter29** [comment]
`PlayState.playerStrums` for player strums
`PlayState.cpuStrums` for player strums

**Comment by Tavish-153** [comment]
how do i pick what strum i wanna use?
