### ISSUE TITLE
Bug Report: I Cant Add Things

### ISSUE THREAD

**Issue by StripeAndFlame** [YoshiCrafter29/YoshiCrafterEngine#186]
## Which target are you using?
- [1 ] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.0
## Please describe your issue. Provide extensive detail and images if possible.
--- It Will Not Let Me Add A Week Button And Scripta

**Comment by YoshiCrafter29** [comment]
**Incomplete issue**
How do i reproduce the step?
Where do you set the scripts
Have you pressed the "Save" button?
Have you made sure everything was ready?
Screenshots?
