### ISSUE TITLE
Bug Report: Elements disappearing when selecting them in the Stage Editor 

### ISSUE THREAD

**Issue by AwesomezPro99** [YoshiCrafter29/YoshiCrafterEngine#189]
So I'm using the latest version of the engine, I went into the Stage Editor to change some stuff. But when I selected the elements they just disappeared even when unselecting them.

## Which target are you using?
Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.1

![Screenshot (482)](https://user-images.githubusercontent.com/103977942/167296631-a273b75d-d133-4d0b-93a4-45d918ff6097.png)

Hopefully it isn't too hard to fix this.

**Comment by YoshiCrafter29** [comment]
Fixed
