### ISSUE TITLE
Bug Report: Combo Counter value is one less than it should

### ISSUE THREAD

**Issue by PhxR3d** [YoshiCrafter29/YoshiCrafterEngine#191]
## Which target are you using?
Windows
## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
It's consistent, regardless of chart or mod.
## Please describe your issue. Provide extensive detail and images if possible.
The combo counter's default value is 0, which causes the combo to be one less than it should be.

**Comment by YoshiCrafter29** [comment]
fixed
