### ISSUE TITLE
Random nulls when saving a chart

### ISSUE THREAD

**Issue by ItsAMeSammieO** [YoshiCrafter29/YoshiCrafterEngine#192]
i was charting a song in this engine, finished it, and decided to port the chart to Psyche Engine so my friends could play it. however upon doing so, the game just instantly crashed. so i look through the json and find that there are random nulls spread across the entire json and deleting these nulls makes the song continue to play as normal.

the nulls are highlighted in orange
![image](https://user-images.githubusercontent.com/43316541/167331206-b52000b1-6f24-4cf2-8af1-0a3c342407eb.png)

is this intentional, or is it just a bug?

**Comment by YoshiCrafter29** [comment]
free up space
