### ISSUE TITLE
Help: HELP!!!!!

### ISSUE THREAD

**Issue by BernardoGP4504** [YoshiCrafter29/YoshiCrafterEngine#193]
#### Please note that the documentation is still under construction.

**Comment by BernardoGP4504** [comment]
and i really need it for a mod/port

**Comment by NicklGames** [comment]
mods/namemod/ui/MainMenuState.hx and etc

**Comment by BernardoGP4504** [comment]
But what to put in the file

Em sáb, 23 de jul de 2022 01:23, NikReta ***@***.***>
escreveu:

**Comment by YoshiCrafter29** [comment]
**To edit existing menus**
`ui/MainMenuState.hx`
`ui/FreeplayState.hx`
`ui/StoryMenuState.hx`

**To override existing menus**
`ui/MainMenuState.hx`
`ui/FreeplayState.hx`

**To create a new state**
`states/name-of-your-state`

```haxe
FlxG.switchState(new ModState("name-of-your-state"));
```
