### ISSUE TITLE
Custom Characters And Stages Result In An Offset Bug

### ISSUE THREAD

**Issue by RetorOtaku** [YoshiCrafter29/YoshiCrafterEngine#201]
## Which target are you using?
Windows
## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.1 - Most recent release
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Currently only using the original stage with no script keeps the offset correct, the bug also doesn't seem to effect any of the original FNF characters, and placing my character in that folder has no effect.
## Please describe your issue. Provide extensive detail and images if possible.
When I activate my song with both my custom stage and character at the same time, my character floats in the air with a large offset, when he hits hits first note, he snaps back to the ground and does his animations as normal. However, his camera positions stay with the large offset. I've only just started to mod FNF - this is my first mod - and I don't really know how to fix this after spending a few hours trying many different solutions, all turning out to fail. Is there a solution or am I just being dumb? :D

Here's a video for proof:

https://user-images.githubusercontent.com/105594142/168476908-01837b2e-0cd6-455a-ae32-0f1aeb036bbb.mp4

**Comment by YoshiCrafter29** [comment]
Make sure that when you're in the stage editor, you click on "Change Dad" and you select your character.

**Comment by RetorOtaku** [comment]
I have

**Comment by RetorOtaku** [comment]
It changes nothing, I have also redone all the character files too, no changes

**Comment by YoshiCrafter29** [comment]
Seems like an issue with the "idle" animation offsets. Go to the character editor, select the "idle" animation and verify if the offsets are correct.

**Comment by RetorOtaku** [comment]
Seems to be fine for me, the glitch only lasts before the first note, but its weird that the camera offsets are permanently affected

**Comment by RetorOtaku** [comment]
So, an update on the situation, I've been fiddling about with the stage, and now the offsets are working fine, its just that now the stage images aren't loading, seems like only one or the other will work

**Comment by YoshiCrafter29** [comment]
mind if you send over your character files?

**Comment by RetorOtaku** [comment]
[Retoro.zip](https://github.com/YoshiCrafter29/YoshiCrafterEngine/files/8695155/Retoro.zip)

This should be all of them

**Comment by RetorOtaku** [comment]
[parkday.zip](https://github.com/YoshiCrafter29/YoshiCrafterEngine/files/8695158/parkday.zip)

Here's the stage too, if you need it

**Comment by YoshiCrafter29** [comment]
Fixed
