### ISSUE TITLE
Help: how do you add a health drain script?

### ISSUE THREAD

**Issue by LeonGamerPS4** [YoshiCrafter29/YoshiCrafterEngine#204]
#### Please note that the documentation is still under construction.
how do you add a script for health drain? i'm making a tabi yoshicrafter port and i need to use this.

**Comment by DelfixYT** [comment]
i also need one of those :)

**Comment by WeldedFlap** [comment]
> ## What do you need help for ?
> #### Please note that the documentation is still under construction.
> how do you add a script for health drain? i'm making a tabi yoshicrafter port and i need to use this.

Continues Over Time:

```function update(elapsed:Float) {
  PlayState.health -= 0.25 * elapsed; // Replace The 0.25 By The Amount Of Health To Drain
}```

When The Dad Player Hits A Note:

```function onDadHit(note:Note) {
  PlayState.health -= 0.25 * FlxG.elapsed; // Replace The 0.25 By The Amount Of Health To Drain
}```

**Comment by YoshiCrafter29** [comment]
```haxe
function onDadHit(note:Note) {
  PlayState.health -= note.isSustainNote ? 0.125 : 0.25;
}
```
