### ISSUE TITLE
Something problem about edit stage jsons

### ISSUE THREAD

**Issue by bz001** [YoshiCrafter29/YoshiCrafterEngine#207]
When I add the custom BGs,and I click it,the BG disappear.Of course,when I click BF,it is either disappeared.So i tried import my BGs into the editor.It occured a error.Is it a bug?

**Comment by YoshiCrafter29** [comment]
Fixed

**Comment by bz001** [comment]
> Fixed

but could you please tell me how can I fix it,because i am facing this problem in the newest version.thanks!

**Comment by YoshiCrafter29** [comment]
select an element, go to the "elements" tab and set the opacity to 1
