### ISSUE TITLE
Bug Report: Week 7 crash

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#211]
After "Ugh" cutscene game crashing
Yoshi Engine V 1.9.1, Windows
![2022-05-22_02-04-51](https://user-images.githubusercontent.com/86905561/169655372-d00c497d-3431-408c-8a4c-7d6705066191.png)

**Comment by YoshiCrafter29** [comment]
Fixed.

Make sure the selected skin actually exists for both the notes and boyfriend.
