### ISSUE TITLE
Bug Report: Lag Spike when hitting first sick w/ Note splashes enabled + Input Responsiveness on Note Dense Charts.

### ISSUE THREAD

**Issue by PhxR3d** [YoshiCrafter29/YoshiCrafterEngine#213]
## Which target are you using?
- Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

All that's need is hitting the first sick in any given song.

## Please describe your issue. Provide extensive detail and images if possible.
When hitting a sick for the first time in a song, it causes the game to lag for a split second, which can throw off the player.

**Comment by PhxR3d** [comment]
Second Issue, in note dense charts, in come cases an input will be missed, causing some misses that aren't due to player error (idk how else to put it)

**Comment by PhxR3d** [comment]
https://youtu.be/LVavcjqj8JQ Here's a video showcasing both issues.

**Comment by YoshiCrafter29** [comment]
All fixed

**Comment by YoshiCrafter29** [comment]
nvm lol

Mind if i get a copy of your Settings.sol ? It's located in %AppData%/YoshiCrafter29/YoshiCrafterEngine/

**Comment by PhxR3d** [comment]
Sorry for the late response to this. I'll send it in a second.

**Comment by PhxR3d** [comment]
Can't send the file itself due to it not being supported, but here's the text that's inside of it. Hope it helps.

oy13:scoreTextSizei16y11:control_2_0i37y11:control_2_1i39y16:showAverageDelayty11:control_4_0i90y11:control_4_1i88y11:control_4_2i190y11:control_6_0i83y13:glowCPUStrumsty16:noteAntialiasingty11:control_4_3i191y11:control_6_1i68y11:control_6_2i70y11:control_8_0i65y16:optimizationTypei1y11:control_6_3i74y9:showTimerty11:control_8_1i83y13:splashesAlphad0.8y17:customScrollSpeedfy13:minimizedModety11:control_6_4i75y11:control_8_2i68y11:control_6_5i76y11:control_8_3i70y28:charter_playerHitsoundVolumed0.333333333333333y11:control_8_4i72y11:control_8_5i74y14:animateMsLabelty23:charEditor_showDadAndBFty11:control_8_6i75y11:control_8_7i76y17:videoAntialiasingty15:greenScreenModefy17:lastInstalledModsay8:CrumbCaty24:Friday%20Night%20Funkin'y23:Funkin'%20Ground%20Zeroy8:SonicEXEy18:YoshiCrafterEnginehy11:arrowColor0i-4043879y11:arrowColor1i-16711681y11:arrowColor2i-15533563y11:arrowColor3i-444097y25:yoshiCrafterEngineCharterty18:charter_showStrumsty20:transparentSubstainsty24:charter_hitsoundsEnabledfy18:alwaysCheckForModsty12:stageQualityi1y26:lastSelectedSongDifficultyi2y11:resetButtonty9:watermarkty10:noteOffseti195y11:selectedModR36y9:autopausety16:combineNoteTypesty17:customArrowColorsty15:checkForUpdatesty6:fpsCapi300y15:smoothHealthbarty12:rainbowNotesfy12:customGFSkiny7:defaulty26:charter_showVoicesWaveformty27:charter_voicesWaveformColori-7078070y21:noteMotionBlurEnabledty26:customArrowColors_allCharsfy14:fps_showMemoryty24:charter_showInstWaveformfy9:noteScalei1y14:emptySkinCachefy11:scrollSpeedd2.5y12:accuracyModezy26:charter_hitsoundsEnabledGFty12:centerStrumsty11:control_1_0i38y11:control_3_0i37y12:middleScrollty11:control_3_1i38y11:control_5_0i90y11:control_3_2i39y11:control_5_1i88y16:hideOriginalGamefy11:control_7_0i83y11:control_5_2i32y16:lastSelectedSongy40:Friday%20Night%20Funkin'%3Asatin-pantiesy12:ghostTappingty11:control_7_1i68y11:control_5_3i190y30:charter_opponentHitsoundVolumed0.333333333333333y13:blammedEffectty10:showMissesty11:control_9_0i65y11:control_7_2i70y11:control_5_4i191y11:control_9_1i83y11:control_7_3i32y11:control_9_2i68y11:control_7_4i74y11:control_9_3i70y11:control_7_5i75y11:control_9_4i32y11:control_7_6i76y25:charter_instWaveformColori-15371265y11:control_9_5i72y13:developerModety15:scoreJoinStringy9:%20%7C%20y11:control_9_6i74y18:memoryOptimizationty11:control_9_7i75y11:control_9_8i76y12:customBFSkiny7:bf-zeroy11:fps_showFPSty12:showAccuracyty17:maxRatingsAllowedi5y16:showAccuracyModety11:maxSplashesi10y6:volumed0.4y17:spawnSplashBehindfy28:autoSwitchToLastInstalledModty14:showPressDelayty26:charter_hitsoundsEnabledBFfy14:animateInfoBarty15:freeplayShowAllfy15:charter_topViewfy18:autoplayInFreeplayfy15:showRatingTotalty16:freeplayCooldowni2y15:splashesEnabledty20:charter_voicesVolumei1y10:downscrollfy24:noteMotionBlurMultiplierd0.8y22:charter_separatorColori-1y18:fps_showMemoryPeakty12:antialiasingty18:charter_instVolumed0.0444444444444444y15:customArrowSkinR63y12:useStressMP4fy10:showRatingty7:botplayfg

**Comment by PhxR3d** [comment]
If there is a way to send the file or something specific I need to do, let me know.

**Comment by YoshiCrafter29** [comment]
Fixed
