### ISSUE TITLE
Bug Report: End Cutscene Glitch

### ISSUE THREAD

**Issue by RetorOtaku** [YoshiCrafter29/YoshiCrafterEngine#220]
## Which target are you using?
Windows
## What version of the engine are you using (Bottom left of the screen in main menu) ?
Most recent
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Currently, no.
## Please describe your issue. Provide extensive detail and images if possible.
End cutscenes are acting very buggy for me, or at least - weird. The end cutscene for my last song still has the screen beats as if it were a song - it doesn't bother me much because it sorta fits with the music, but I'm assuming it's not meant to happen. Also end cutscenes if not placed on the last song instantly crash the game and make it impossible to close.
Or, all of this could just amount to me being stupid.

![NotFinalSong](https://user-images.githubusercontent.com/105594142/171863925-63955ac5-9bf7-403b-9006-6d33d87f225a.png)

https://user-images.githubusercontent.com/105594142/171864331-344cd2da-374f-4b41-a431-f2c3266addce.mp4

**Comment by ItsyourboyJonnycat** [comment]
remove the line 2081 from playstate that should fix it

**Comment by YoshiCrafter29** [comment]
fixed
