### ISSUE TITLE
Bug Report: Regular Combo Graphic Shown in Pixel Stages, as well as normal numbers being shown on combo reset/initial combo.

### ISSUE THREAD

**Issue by PhxR3d** [YoshiCrafter29/YoshiCrafterEngine#221]
## Which target are you using?
- Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Play any of the pixel songs.

## Please describe your issue. Provide extensive detail and images if possible.
The combo graphic is the normal version instead of the pixel version, and the combo number also shows as the normal version of the numbers when the combo is started or reset.

**Comment by YoshiCrafter29** [comment]
fixed
