### ISSUE TITLE
Help: Engine Noob :(

### ISSUE THREAD

**Issue by DelfixYT** [YoshiCrafter29/YoshiCrafterEngine#222]
#### Please note that the documentation is still under construction.
EVERYTHING im new to the engine but: i cant figure out how tf i make a sustain note lol
![image](https://user-images.githubusercontent.com/92229617/172230095-dc6b77db-7c74-4c7c-88ae-3c0801258a09.png)

**Comment by FoxelTheFennic** [comment]
click and drag down with your mouse cursor

**Comment by BernardoGP4504** [comment]
put the note or [Ctrl] + click it and drag with the mouse (recommended) or use the scroll wheel

**Comment by YoshiCrafter29** [comment]
Click and drag down
