### ISSUE TITLE
Enhancement: Add an event to change the keys mid-song, or start with more keys.

### ISSUE THREAD

**Issue by K1ZANA** [YoshiCrafter29/YoshiCrafterEngine#224]
#### Please check for duplicates or similar issues before creating this issue. 

- [x] Did that.

## What is your suggestion, and why should it be implemented?
---

I´d suggest to add an option in the chart editor to change the number of keys.
With pre-set options, or to enter your own number of keys.
[1-9]

##### Why should it be implemented?
---
Well, it makes it easier to code something with more keys.
Since as far as i know its kinda hard to implement that yourself.

**Comment by oisintheblue** [comment]
its already added, except it only used left down up right arrows, and n ot the special funni diamond arrows

**Comment by K1ZANA** [comment]
OHHHH alright, i didnt notice that!

Am Mo., 13. Juni 2022 um 04:04 Uhr schrieb oisintheblue <
***@***.***>:

**Comment by K1ZANA** [comment]
Imma close this now, thanks!
