### ISSUE TITLE
Enhancement: Mods within mods???

### ISSUE THREAD

**Issue by PhxR3d** [YoshiCrafter29/YoshiCrafterEngine#231]
## What is your suggestion, and why should it be implemented?
Ok so this is gonna sound really unnecessary but I figured I could at least suggest it.
So the thought is that you can add mods onto a mod you've already created. Let me give an example.
Say I have a remix mod, and the mod itself is just the normal FNF weeks.
But let's say I decide to do a remix of another mod, and I don't want it to be apart of the main mod, but still want it to be available in case people wanna play it.
Being able to have mod add ons for other mods would allow the ability to use what's already present in a mod to create another, and might also help with not needing to have the same assets for multiple mods. Pretty sure this won't be implemented but I figured I should at least suggest it.

**Comment by blissedandpissed** [comment]
Oh, sorta like DLC for Funkin' Is Magic? That sound's cool. I'll push this on the discord.

**Comment by YoshiCrafter29** [comment]
Might seems like a good idea, however this would push the mods folder to a certain point where it would cause performance issues.
