### ISSUE TITLE
Enhancement: Dialogues

### ISSUE THREAD

**Issue by LeonGamerPS4** [YoshiCrafter29/YoshiCrafterEngine#232]
## What is your suggestion, and why should it be implemented?
--- i would really like for dialogues, along with an editor for dialogues to be implemented. this is easier than using cutscenes as dialogues.

**Comment by BernardoGP4504** [comment]
there's already a way to do this but it's really complicated to make it work

**Comment by FoxelTheFennic** [comment]
this is being added in the 2.0 update

**Comment by YoshiCrafter29** [comment]
I GET IT!!!
