### ISSUE TITLE
Help: How do you make the bar do THIS?

### ISSUE THREAD

**Issue by LeonGamerPS4** [YoshiCrafter29/YoshiCrafterEngine#234]
#### Please note that the documentation is still under construction.
I need one final script for my port of tabi to this engine, and i need help with implementing tabi’s genocide health bar mechanic. here’s what it looks like (if you didn’t know, although most of you already know)
![image](https://user-images.githubusercontent.com/98667115/174703260-4de24638-2d18-4fea-9d9e-79f4acafa63e.jpeg)

**Comment by YoshiCrafter29** [comment]
```haxe
function createPost() {
   PlayState.maxHealth = 3;
   PlayState.healthBar.setRange(0, 2);
}
function update(elapsed:Float) {
   PlayState.healthBar.x = ((FlxG.width - PlayState.healthBar.width) / 2) - ((PlayState.healthBar.width / 2) * (FlxMath.bound(FlxMath.remapToRange(PlayState.health, 2, 3, 0, 1), 0, 1)));
   PlayState.healthBarBG.setPosition(PlayState.healthBar.x - 4, PlayState.healthBar.y - 4);
}
```
