### ISSUE TITLE
Bug Report: Can't create a stage without and xml

### ISSUE THREAD

**Issue by MabsootNG** [YoshiCrafter29/YoshiCrafterEngine#239]
I've tried multiple times to make sure it wasn't a one-time thing, I've made a stage without needing an XML. I'm even using the same file and just replacing one thing.

**Comment by YoshiCrafter29** [comment]
You mean adding a png file crashes the engine because its xml doesnt exists? This bug has been fixed in 2.0.0.

**Comment by MabsootNG** [comment]
ah i apologize for wasting your time, ill download the update

**Comment by YoshiCrafter29** [comment]
its fine lol
