### ISSUE TITLE
Bug Report: [copy last section kills yoshi 2.00]

### ISSUE THREAD

**Issue by AMNOTSIRVOID** [YoshiCrafter29/YoshiCrafterEngine#240]
## Which target are you using?
- [x] linux

## Please describe your issue. Provide extensive detail and images if possible.
       (it dies when you copy last section.)
---

**Comment by AMNOTSIRVOID** [comment]
![Screenshot_2022-07-03_12-44-54](https://user-images.githubusercontent.com/88630349/177049637-0b20035e-8697-4ae3-95c6-e6a8df13855a.png)

**Comment by YoshiCrafter29** [comment]
fixed
