### ISSUE TITLE
Help: Not all keybinds in charting menu work

### ISSUE THREAD

**Issue by NicklGames** [YoshiCrafter29/YoshiCrafterEngine#242]
#### Please note that the documentation is still under construction.

Idk if I'm doing something wrong, but when I press, for example, E or A to change the note's sustain length, nothing would happen

**Comment by YoshiCrafter29** [comment]
drag the note on the charter grid to make a sustain

**Comment by NicklGames** [comment]
> drag the note on the charter grid to make a sustain

@YoshiCrafter29 what version was that invented in? im using 1.9.0

**Comment by YoshiCrafter29** [comment]
for off beat notes just shift click
