### ISSUE TITLE
Help: How to check for a note type/name in song script?

### ISSUE THREAD

**Issue by NicklGames** [YoshiCrafter29/YoshiCrafterEngine#244]
#### Please note that the documentation is still under construction.

let's say i have a script that plays on Bopeebo, i add the onDadHit() function and want to do smth if certain note type is hit
![image](https://user-images.githubusercontent.com/60806448/177514482-bf933a87-2998-4a3a-a32d-5621ffd7096a.png)
how can i check for note type/name?

**Comment by YoshiCrafter29** [comment]
note.noteType is the index of the note's note type
For example, if you added 2 note types in the charter (for example: `Default Note` and `Hurt Note`), `Default Note` will have an index of 0 and `Hurt Note` will have an index of 1.
Hope that helped.

**Comment by NicklGames** [comment]
> note.noteType is the index of the note's note type For example, if you added 2 note types in the charter (for example: `Default Note` and `Hurt Note`), `Default Note` will have an index of 0 and `Hurt Note` will have an index of 1. Hope that helped.

for some reason it does not work.. hm
![image](https://user-images.githubusercontent.com/60806448/177540180-8adcc1bd-f285-4a71-af42-e1fffdc18b5a.png)
these are the notes added in chart editor ^
![image](https://user-images.githubusercontent.com/60806448/177540284-4071c3cf-d403-4088-8327-33fbba7c363d.png)
and this is the code that SHOULD be called if they're pressed ^

but eightbit does not play any animation

**Comment by YoshiCrafter29** [comment]
note.noteData % 4?

Or do this:
`global["eightbit"] = eightbit;`
And add this in your note script (8bit Note.hx):
```haxe
function onDadHit(direction:Int) {
     switch(direction) {
        case 0:
            global["eightbit"].playAnim("singLEFT", true);
        case 1:
            global["eightbit"].playAnim("singDOWN", true);
        case 2:
            global["eightbit"].playAnim("singUP", true);
        case 3:
            global["eightbit"].playAnim("singRIGHT", true);
     }
}
```
