### ISSUE TITLE
Enhancement: upload compiled version

### ISSUE THREAD

**Issue by KazuiShoto** [YoshiCrafter29/YoshiCrafterEngine#245]
## What is your suggestion, and why should it be implemented?
---
it's so hard to compile and so confusing, I certainly don't know how to do it, and a lot of people probably don't as well. Not to mention if you upload a compiled version it would be easier for people to pick up the engine and give it a try

**Comment by YoshiCrafter29** [comment]
https://github.com/YoshiCrafter29/YoshiCrafterEngine/releases/tag/v2.0.0b
its already here
