### ISSUE TITLE
Bug Report: Change BMP in selection dont change chart grid/speed

### ISSUE THREAD

**Issue by Foxplort** [YoshiCrafter29/YoshiCrafterEngine#246]
## Which target are you using?
Windows

## What version of the engine are you using?
**1.9.0
2.0.0 BETA**

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Try changing the BMP in the chart editor (for selection).

## Please describe your issue. Provide extensive detail and images if possible.
Changing the BMP in the selection does not affect the chart editor speed. In the original game, this affects the placement of the notes and the scrolling speed of the selection.

**Comment by YoshiCrafter29** [comment]
its being fixed rn
