### ISSUE TITLE
Help: How to change amount of health player gets on hit?

### ISSUE THREAD

**Issue by NicklGames** [YoshiCrafter29/YoshiCrafterEngine#249]
#### Please note that the documentation is still under construction.

I have an idea for a special note type that, WHEN HIT: reduces the amount of health player gets via hitting notes

**Comment by YoshiCrafter29** [comment]
```haxe
function onPlayerHit(direction:Int) {
    for(e in PlayState.ratings)
       e.health *= 0.75;
}
```
