### ISSUE TITLE
Bug Report: Long Note Bug

### ISSUE THREAD

**Issue by AnonymousUser351** [YoshiCrafter29/YoshiCrafterEngine#252]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
v1.9.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Just hold down all the keys
## Please describe your issue. Provide extensive detail and images if possible.
---
If you just hold down all of the keys, you'll miss the beginning of the note but hit the sustain.

**Comment by Volta07** [comment]
thats not a bug thats supposed to do that

**Comment by BernardoGP4504** [comment]
> thats not a bug thats supposed to do that
it's not supposed to do that

**Comment by BernardoGP4504** [comment]
also, this is a input bug that came from the actual friday night funkin' without it being any engine

**Comment by YoshiCrafter29** [comment]
Intentional.
