### ISSUE TITLE
Bug Report: No credits to load causes crash

### ISSUE THREAD

**Issue by ThatOneIdiotXav** [YoshiCrafter29/YoshiCrafterEngine#254]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
v2.0.0 BETA

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Changed the name of the credits.json file for both the _Friday Night Funkin'_ mod and the file outside of _mods/_.
[Image of Null Object Reference](https://i.imgur.com/4o2mZby.png)
[Image of the credits.json file outside of mods/ renamed](https://i.imgur.com/ttXCPJ9.png)
[Image of the credits.json file in the _Friday Night Funkin'_ mod renamed](https://i.imgur.com/sMB6C4J.png)

## Please describe your issue. Provide extensive detail and images if possible.
---
The game crashes whenever there's no credits to load at all, causing a Null Object Reference.

**Comment by BernardoGP4504** [comment]
the file HAS to be named **`credits.json`**

**Comment by ThatOneIdiotXav** [comment]
> the file HAS to be named **`credits.json`**

I know that, but I'm simply saying that there's nothing to basically prevent it from crashing when there is none.

**Comment by BernardoGP4504** [comment]
Then uh, idk 😶

Em qua, 13 de jul de 2022 19:38, Xav ***@***.***> escreveu:

**Comment by YoshiCrafter29** [comment]
Theres nothing to prevent it cause you aren't supposed to edit those. The 2 files you renamed are from the FNF "mod" itself and the YoshiCrafter Engine credits.
If you want to mess with credits, just do it in your own mod.
