### ISSUE TITLE
Enhancement: being able to add animation indices in character editor

### ISSUE THREAD

**Issue by crispyboi24** [YoshiCrafter29/YoshiCrafterEngine#255]
This should be a cool lil feature so you can make custom gfs in the character editor

**Comment by BernardoGP4504** [comment]
no need as you could modify the `.json` file to be `indices: [your indices here],`

**Comment by crispyboi24** [comment]
it would still be useful

**Comment by blissedandpissed** [comment]
> no need as you could modify the `.json` file to be `indices: [your indices here],`

That's not the point, many other engines such as Psych have indices built into the character editor, Yoshi not having it is a major setback and makes things such as a custom girlfriend significantly harder as you essentially need to eye your animation. 

A possible implementation could have a frame viewer, where you can select some frames and make them into an animation.

**Comment by BernardoGP4504** [comment]
What do you mean psych has that, it just doesn't.

Em qua, 20 de jul de 2022 06:40, blissedandpissed ***@***.***>
escreveu:

**Comment by YoshiCrafter29** [comment]
its in
