### ISSUE TITLE
Help: how do i change the scroll speed

### ISSUE THREAD

**Issue by BernardoGP4504** [YoshiCrafter29/YoshiCrafterEngine#258]
#### Please note that the documentation is still under construction.
i want to create a note that when hit changes the scroll speed of the whole chart to be more faster

**Comment by Reycko** [comment]
i guess you could just script that to change the scroll speed at a certain time

**Comment by YoshiCrafter29** [comment]
```haxe
PlayState.SONG.speed = scrollSpeed;
```
or if you want to set it for a specific strum
```haxe
getStrum(id).scrollSpeed = scrollSpeed;
```

**Comment by BernardoGP4504** [comment]
Not this way, i wanted to do it like whenever this note is hit it changes
the scroll speed by 0.5

Em ter, 19 de jul de 2022 17:48, YoshiCrafter29 ***@***.***>
escreveu:
