### ISSUE TITLE
Help: Camera detection

### ISSUE THREAD

**Issue by BernardoGP4504** [YoshiCrafter29/YoshiCrafterEngine#259]
#### Please note that the documentation is still under construction.
hi, how can i detect the camera (i'm making a camera zoom event)

**Comment by YoshiCrafter29** [comment]
`FlxG.camera`

**Comment by BernardoGP4504** [comment]
> `FlxG.camera`

using this would crash the game with the message `null object reference` thhe script was:
```
function create(zoom:Int) {
    FlxG.camera *= zoom;
}
```
