### ISSUE TITLE
Bug Report: Custom stage results in 2 bugs

### ISSUE THREAD

**Issue by BernardoGP4504** [YoshiCrafter29/YoshiCrafterEngine#260]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.9.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
i loaded my stage in another song
## Please describe your issue. Provide extensive detail and images if possible.
---
so, i was making a stage for a song (by copying the stage files from another stage and then in-game replacing the assets) and whenever i load the stage, it looks like the other stage:
## how it should look like:
![Captura de Tela (15)](https://user-images.githubusercontent.com/101405920/179085586-a370a07b-80d0-497a-a80a-ca0602b58c76.png)
## how it is:

https://user-images.githubusercontent.com/101405920/179087620-03a3368c-3516-471d-9987-5c14ddeab08d.mp4

(sorry for lag, forgot to set my obs settings)
the second bug was the opponent floating before he hit a note

**Comment by YoshiCrafter29** [comment]
second bug was fixed, first one was caused by you using the wrong stage or not saving.

**Comment by BernardoGP4504** [comment]
I got the first one fixed but the second bug still happens
