### ISSUE TITLE
Bug Report: Play Here button in charter causes crash

### ISSUE THREAD

**Issue by ThatOneIdiotXav** [YoshiCrafter29/YoshiCrafterEngine#262]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
v2.0.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

- Enter the Chart Editor
- Press _Play Here_
- Crash occurs

## Please describe your issue. Provide extensive detail and images if possible.
---
Pressing the Play Here button in the charter causes a crash.
[Video to demonstrate](https://streamable.com/x7qzpp)

**Comment by YoshiCrafter29** [comment]
added null checks
