### ISSUE TITLE
Help: How to make Skid'n'Pump-like idle work?

### ISSUE THREAD

**Issue by NicklGames** [YoshiCrafter29/YoshiCrafterEngine#264]
#### Please note that the documentation is still under construction.

i added all the animations (danceLeft, danceRight + singings) but the character always just freezes in the last pose they were singing
![image](https://user-images.githubusercontent.com/60806448/179683593-88da623d-b4bf-485e-9e9f-3d3a909ef715.png)
(this is down pose)

**Comment by YoshiCrafter29** [comment]
on 2.0.0 just add the danceLeft and danceRight anims and it'll work automatically

**Comment by NicklGames** [comment]
> on 2.0.0 just add the danceLeft and danceRight anims and it'll work automatically

can i just copypaste the mod from 1.9.smth to 2.0?
