### ISSUE TITLE
Bug Report: Copying Sections Doesn't Work Normally

### ISSUE THREAD

**Issue by AnonymousUser351** [YoshiCrafter29/YoshiCrafterEngine#271]
## Which target are you using?
- [x] Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
v2.0.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Select press the Copy button on the left side of the chart editor, and press Paste in a different section.
## Please describe your issue. Provide extensive detail and images if possible.
--- Copying and Pasting sections doesn't work normally. Before 2.0.0, you would be able to paste a section into a different section just fine. After 2.0.0, changes aren't shown properly. The pasted section doesn't appear in the chart editor until you restart the Chart Editor State. This is a problem since you won't be able to see what you already copied and what you haven't.

**Comment by YoshiCrafter29** [comment]
Fixed
