### ISSUE TITLE
Bug Report: Still can't type anything in the Toolbox

### ISSUE THREAD

**Issue by AnonymousUser351** [YoshiCrafter29/YoshiCrafterEngine#272]
## Which target are you using?
- [x] Windows
## What version of the engine are you using (Bottom left of the screen in main menu) ?
v2.0.2
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
I can't type anything except for Backspace.
## Please describe your issue. Provide extensive detail and images if possible.
--- Why is this still an issue??

https://user-images.githubusercontent.com/86208538/180014884-9db9acd5-6e48-4ea6-bf18-a388d586c3c4.mp4

**Comment by YoshiCrafter29** [comment]
restart the engine or press F6 to close then open back the logs

it should be fixed
