### ISSUE TITLE
Help:  Source Code

### ISSUE THREAD

**Issue by adamsaustria** [YoshiCrafter29/YoshiCrafterEngine#274]
using source code to compile engine for my computer https://cdn.discordapp.com/attachments/998113684285034508/999040686676529242/Screenshot_2022-07-19_at_2.50.47_PM.png

**Comment by YoshiCrafter29** [comment]
dont use source code lol

theres enough stuff in the engine so that everything you need can be softcoded, just look at vs blackjack!
