### ISSUE TITLE
Long songs bug out the game

### ISSUE THREAD

**Issue by ItsAMeSammieO** [YoshiCrafter29/YoshiCrafterEngine#276]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.0.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Any song longer than 25:20 should reproduce the bug

## Please describe your issue. Provide extensive detail and images if possible.
---
I've been having this problem where charting a long song completely bugs out the game. For context, I decided I wanted to chart Splitathon 2 for fun and got this problem when first starting out.
These bugs include:
- Freezing every characters animations 
- Notes no longer appear after the beginning countdown
- Causes the timer to read "0:00 / -6:-4"
- Causes the charter to completely disappear as you press space
However the song still continues to play, and you can still press down notes.
Video:

https://user-images.githubusercontent.com/43316541/180296687-c6c0264f-4add-45cc-acc5-49106b8fdd05.mp4

**Comment by SrtHero278** [comment]
Someone said this in Psych Engine but the reason was a haxeflixel thing.

https://github.com/ShadowMario/FNF-PsychEngine/issues/9827#issuecomment-1190683292

**Comment by YoshiCrafter29** [comment]
HaxeFlixel limit.

You can perhaps split the song into multiple parts that are loaded during the song itself
