### ISSUE TITLE
Bug Report: Custom character set has GF and Opponent causes it to make 2 rather then 1

### ISSUE THREAD

**Issue by dylan012006** [YoshiCrafter29/YoshiCrafterEngine#278]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
I'm using 2.0.2
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
If you go into the tutorial and set the gf and opponent to a custom character, there will be 2 of the same character instead of 1

## Please describe your issue. Provide extensive detail and images if possible.
So i was on 2.0.2 while making a mod and i noticed that for some reason the custom character who is set as the opponent and the gf causes it to make 2 of the same character rather then to make it one character. And along with that, it didn't happen back on 1.9.1.

This is what it's supposed to do back in 1.9.1
![image](https://user-images.githubusercontent.com/61915388/180326667-3bd519cd-dcd1-46c8-b9de-a50bb55bb9c3.png)

This is what happened in 2.0.2
![image](https://user-images.githubusercontent.com/61915388/180326681-c08a3e94-f081-496c-b627-29c37d5aa94f.png)
(don't question the characters-)
I don't know if this is intentional or not this is my first time writing an issue on GitHub and idk if it's a bug or not-

**Comment by YoshiCrafter29** [comment]
That's actually intentional

If you want a workaround for this, rename your character to something that starts with `gf`, or paste this in a script:
```haxe
function createPost() {
   dad.setPosition(gf.x, gf.y);
   gf.visible = false;
}
```
