### ISSUE TITLE
Help: danceLeft danceRight animations dont work on 2.0

### ISSUE THREAD

**Issue by NicklGames** [YoshiCrafter29/YoshiCrafterEngine#279]
#### Please note that the documentation is still under construction.

the animations are added, they work in character editor
![image](https://user-images.githubusercontent.com/60806448/180370001-bbbce9fa-ccd5-4f5a-9ad0-ddf0c4111134.png)

but in game they still dont
![image](https://user-images.githubusercontent.com/60806448/180369878-8fd707fc-071b-43c5-b6bf-886c32e45c77.png)

**Comment by YoshiCrafter29** [comment]
Open your Character.json and replace `"danceSteps": null` by `"danceSteps" : ["danceLeft", "danceRight"]`

**Comment by NicklGames** [comment]
> Open your Character.json and replace `"danceSteps": null` by `"danceSteps" : ["danceLeft", "danceRight"]`

it is like that, but still no result
![image](https://user-images.githubusercontent.com/60806448/180589560-1a54b76d-b400-4ff8-93b4-212068035243.png)
