### ISSUE TITLE
Bug Report: Notes can't be placed correctly on Change BPM sections

### ISSUE THREAD

**Issue by swordcube** [YoshiCrafter29/YoshiCrafterEngine#283]
## Which target are you using?
I am using Windows.

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.0.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Make a section change BPM and try to place notes

## Please describe your issue. Provide extensive detail and images if possible.
I am currently trying to chart a song but i am unable to finish the chart correctly because a bug happens where if you try to place notes on a change bpm section, they all become really long sustains with just a single click (I don't think you can change the length of them either)

https://user-images.githubusercontent.com/49110074/180519474-99e5fde0-78a9-49b2-b78d-f199cacc9d53.mp4

**Comment by YoshiCrafter29** [comment]
Fixed

**Comment by swordcube** [comment]
> Fixed

well you see

https://user-images.githubusercontent.com/49110074/180849770-5d3fd1c7-ce33-4934-a2b2-3797dec85357.mp4
