### ISSUE TITLE
Help: How to reset progress for played songs and for medals

### ISSUE THREAD

**Issue by NicklGames** [YoshiCrafter29/YoshiCrafterEngine#286]
#### Please note that the documentation is still under construction.

Let's say im done with the mod, ofc i played all the songs. How do I reset the progress for them so that other players wont see MY score before they even play the mod?

**Comment by YoshiCrafter29** [comment]
mod save isn't saved in your `mods` folder, instead it is saved in `%AppData%\YoshiCrafter29\YoshiCrafterEngine`
which means if you release your mod, other players won't be able to see your score.
