### ISSUE TITLE
Bug Report: MacOS Compile error

### ISSUE THREAD

**Issue by BushTrain460615** [YoshiCrafter29/YoshiCrafterEngine#287]
##### PS : the "everything goes black while changing state in developer mode bug" is not a bug, it's been designed this way to refresh all bitmaps between states to allow easier modding.

I put what shows up in the terminal here

Error: ./src/PlayState.cpp:6731:86: error: conditional expression is ambiguous; '::Dynamic' can be converted to '::Character' (aka 'ObjectPtr<Character_obj>') and vice versa
                if (HX_FIELD_EQ(inName,"dad") ) { return ::hx::Val( inCallProp == ::hx::paccAlways ? get_dad() : dad ); }
                                                                                                   ^ ~~~~~~~~~   ~~~
./src/PlayState.cpp:6799:92: error: conditional expression is ambiguous; '::Dynamic' can be converted to '::Boyfriend' (aka 'ObjectPtr<Boyfriend_obj>') and vice versa
                if (HX_FIELD_EQ(inName,"boyfriend") ) { return ::hx::Val( inCallProp == ::hx::paccAlways ? get_boyfriend() : boyfriend ); }
                                                                                                         ^ ~~~~~~~~~~~~~~~   ~~~~~~~~~
./src/PlayState.cpp:6809:92: error: conditional expression is ambiguous; '::Dynamic' can be converted to 'Float' (aka 'double') and vice versa
                if (HX_FIELD_EQ(inName,"accuracy_") ) { return ::hx::Val( inCallProp == ::hx::paccAlways ? get_accuracy_() : accuracy_ ); }
                                                                                                         ^ ~~~~~~~~~~~~~~~   ~~~~~~~~~
3 errors generated.
Picture
<img width="1044" alt="Screenshot 2022-07-23 at 12 36 22 AM" src="https://user-images.githubusercontent.com/72326501/180592049-df21740b-2e19-479f-a397-c782b8a42cab.png">

**Comment by YoshiCrafter29** [comment]
![image](https://user-images.githubusercontent.com/81191621/180626309-09af898c-d754-4c61-a0b6-f75b8eef6aca.png)
Seems like a haxe compiler issue, can't do anything about it.
Try reporting it to hxcpp
