### ISSUE TITLE
Enhancement: Camera follow character notes option

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#289]
a new Option in Options > Customization menu, if on - camera will be following notes character hit, like in a lot of mods

**Comment by YoshiCrafter29** [comment]
You can already do that manually with scripts
```haxe
for(c in [boyfriend, gf, dad]) {
   c.addCameraOffset("singUP", 0, -50);
   c.addCameraOffset("singDOWN", 0, 50);
   c.addCameraOffset("singLEFT", -50, 0);
   c.addCameraOffset("singRIGHT", 50, 0);
}
```
adding this as a main option would prob break some scripts, so i'm not adding it in.
