### ISSUE TITLE
Bug Report: Sustain Notes Don't Do Damage

### ISSUE THREAD

**Issue by Levka4** [YoshiCrafter29/YoshiCrafterEngine#290]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as deleting the YoshiCrafter29 folder from AppData) before submitting an issue.
I've deleted this folder before bug report.
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.0.2
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Play any song that has sustain notes and just press it (without holding).
## Please describe your issue. Provide extensive detail and images if possible.
This problem doesn't appear in version 2.0.0. In 2.0.2 sustain notes don't do damage.

**Comment by YoshiCrafter29** [comment]
fixed
