### ISSUE TITLE
Bug Report: Chartacter edditing bug

### ISSUE THREAD

**Issue by chillultimated** [YoshiCrafter29/YoshiCrafterEngine#292]
When I added a character and wanted to edit it this happend
![2022-07-24_18-54-58](https://user-images.githubusercontent.com/86905561/180636195-71fe20fe-c649-4e91-94af-0e716e5174ce.png)

And when I opened Animations adding menu game crushed

Which target are you using?
Windows

What version of the engine are you using (Bottom left of the screen in main menu) ?
2.0.2

**Comment by YoshiCrafter29** [comment]
can i get a video, the error message that pops up and steps to reproduce that?

**Comment by chillultimated** [comment]
> can i get a video, the error message that pops up and steps to reproduce that?

theres no any error, game just crushed

**Comment by chillultimated** [comment]
> can i get a video, the error message that pops up and steps to reproduce that?

also that happend only 1 time and idk what was that, do you any ideas?

**Comment by YoshiCrafter29** [comment]
seems like a flixel bug.
