### ISSUE TITLE
Help: week detection (read the post)

### ISSUE THREAD

**Issue by BernardoGP4504** [YoshiCrafter29/YoshiCrafterEngine#293]
#### Please note that the documentation is still under construction.
how can i detect from what week the song is from (for a freeplay menu)

**Comment by YoshiCrafter29** [comment]
`PlayState.actualModWeek`

its a structure with these parameters:
![image](https://user-images.githubusercontent.com/81191621/180662425-b2773dc5-1b49-4e6f-a169-63af379eea18.png)

**Comment by BernardoGP4504** [comment]
> PlayState.actualModWeek

but everytime i use it it says:
`invalid access to field actualModWeek` am i doing something wrong?

**Comment by BernardoGP4504** [comment]
i'm trying to use it like
```haxe
if (PlayState.actualModWeek == 'weekendX')
```
is this right?
