### ISSUE TITLE
Help: how do i set the order of the menu options

### ISSUE THREAD

**Issue by BernardoGP4504** [YoshiCrafter29/YoshiCrafterEngine#294]
#### Please note that the documentation is still under construction.
already in title
like, i just added a menu option called gallery using `MainMenuState.hx` but i don't know how to set the order of the options

**Comment by YoshiCrafter29** [comment]
copy `mainMenu.json` from `mods/Friday Night Funkin'/data` to `mods/your mod/data`, then add the option here,
name the callback smth like `onCredits` so that in MainMenuState.hx you can do this:
```haxe
function onCredits() {
   // switch to credits
}```
