### ISSUE TITLE
Text isn't working properly

### ISSUE THREAD

**Issue by Brad2024** [YoshiCrafter29/YoshiCrafterEngine#298]
![Friday Night Funkin' 7_24_2022 11_17_21 PM](https://user-images.githubusercontent.com/91802378/180711513-e5344e4e-efea-4f4f-bf55-456f9bc21b72.png)

**Comment by YoshiCrafter29** [comment]
Judging by how you ported B-Sides, you probably overridden one of the alphabet files in the mods folder with something else, completely breaking the thing.
