### ISSUE TITLE
Bug Report: Week 7 stress cutscene crashes the game

### ISSUE THREAD

**Issue by qdartheawesomeman** [YoshiCrafter29/YoshiCrafterEngine#301]
hello, i was currently playing week 7 version of the yoshicrafterengine.
when i finished the Guns Song it was supposed to get to the next song but the game crashes before the cutscene began.
so i just encountered this issue.
please fix it.

**Comment by qdartheawesomeman** [comment]
Also my version of the yoshicrafterengine is 2.0.3 the recent updated one

**Comment by blissedandpissed** [comment]
this is most likely an issue with your computer, the stress cutscene is quite resource intensive as it is animated realtime by your computer, so i would enable "mp4 cutscene for stress" in the optimisation settings

**Comment by qdartheawesomeman** [comment]
there's one problem...
there is no MP4 Cutscene for stress button in the optimisation settings
my version of the engine is 2.0.3

**Comment by blissedandpissed** [comment]
> there's one problem... there is no MP4 Cutscene for stress button in the optimisation settings my version of the engine is 2.0.3

turn on advanced options in the miscellaneous settings and then go to the optimisation settings to turn on the mp4 cutscene

**Comment by qdartheawesomeman** [comment]
well i wasn't talking about turning on the mp3...i was talking about this
![bandicam 2022-07-30 15-14-24-040](https://user-images.githubusercontent.com/71853801/181913814-5de8dec9-779d-46ad-947d-da141622042e.jpg)

**Comment by YoshiCrafter29** [comment]
fixed
