### ISSUE TITLE
Not necessarily a bug, but rather an engine issue (Memory Leaking)

### ISSUE THREAD

**Issue by BombasticTom** [YoshiCrafter29/YoshiCrafterEngine#309]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
- I am using the latest version 2.2.0b

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
- This bug can occur anywhere in the game (mostly while in Play State)

## Please describe your issue. Provide extensive detail and images if possible.
- The memory leaks a lot casually or just when hitting the notes (jumps about up to 3 more megabytes of ram usage), and there's a common framerate drop while playing. I haven't really noticed any framerate drop in earlier versions, nor have I seen anyone opening a similar issue. (PS, I am not on a potato PC)

**Comment by YoshiCrafter29** [comment]
reduced memory usage (and fps drops) when note are hit
