### ISSUE TITLE
Bug Report: Judgements making me look like I have a skill issue or I just don't get them at all

### ISSUE THREAD

**Issue by CrusherNotDrip** [YoshiCrafter29/YoshiCrafterEngine#311]
## Which target are you using?
- [ ] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.2.0b

## Please describe your issue. Provide extensive detail and images if possible.
- Basically when I use my main controls (QWOP) I hit sicks and goods BUT when I use my arrow keys (secondary controls) it has a temper so I either hit all shits or nothing at all. (the nothing at all part happens when I pause the game sometimes) this video shows it all:

https://user-images.githubusercontent.com/90648119/188357969-70437ce9-f938-4f71-85b7-c3036a269fb8.mp4

**Comment by YoshiCrafter29** [comment]
oh yeah, secondary controls aren't fully functioning (i forgot they existed tbf)
fixed that issue
