### ISSUE TITLE
Bug Report: [Null Object When Skip Update By Pressing Shift+Enter]

### ISSUE THREAD

**Issue by mateus683** [YoshiCrafter29/YoshiCrafterEngine#314]
I did download the most recent version from yoshi crafter engine and i saw at the update log that i could skip the update by pressing shift+enter but when i did that it appeared a null object reference.
The crash:
An error occured !
YoshiCrafter Engine ver. 2.2.0b 

Null Object Reference
 
Called from ModSupport.refreshDiscordRpc (ModSupport.hx line 101)
Called from MusicBeatState.new (MusicBeatState.hx line 73)
Called from mod_support_stuff.FullyModState.new (mod_support_stuff/FullyModState.hx line 12)
Called from MainMenuState.new (MainMenuState.hx line 47)
Called from TitleState.update (TitleState.hx line 385)
Called from flixel.util.FlxTimer.onLoopFinished (flixel/util/FlxTimer.hx line 195)
Called from flixel.util.FlxTimerManager.update (flixel/util/FlxTimer.hx line 285)
Called from flixel.FlxGame.update (flixel/FlxGame.hx line 756)
Called from flixel.FlxGame.step (flixel/FlxGame.hx line 688)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 556)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1399)

The engine is still in it's early stages, so if you want to report that bug, go ahead and create an Issue on the GitHub page !

**Comment by YoshiCrafter29** [comment]
fixed
