### ISSUE TITLE
Help: Moving Note Strums

### ISSUE THREAD

**Issue by PumpTutorials** [YoshiCrafter29/YoshiCrafterEngine#318]
How would I make notes move? (I would prefer in haxe)
Can someone help me with this?

Examples:
https://user-images.githubusercontent.com/73810550/147987067-d99ddbbe-ae98-4293-948c-3bb7f4c61335.mp4
https://www.youtube.com/watch?v=z20bwocgrC8

**Comment by YoshiCrafter29** [comment]
`getStrum(id)` will return a strum (gray note) that you'll be able to move by changing their `x` and `y` positions.
you can also set the angle via `angle` and force a note scroll angle via `notes_angle`

**Comment by PumpTutorials** [comment]
that doesnt really help but something that would help is tweening this:

function beatHit(curBeat) {
    for (i in 0...8) {
        PlayState.playerStrums.members[1].x += 32 * Math.sin(curBeat + i*2);
    }
}
