### ISSUE TITLE
Bug Report: all ratings turn into shit ratings when spamming any keybinds and then using arrow keys

### ISSUE THREAD

**Issue by pizzapwner** [YoshiCrafter29/YoshiCrafterEngine#319]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?

2.2.0b

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

First, enter any song.
Then, spam whatever your keybinds are, and after spamming for like 1 second or so, use the arrow keys as your controls and everything should rate you as a shit rating
## Please describe your issue. Provide extensive detail and images if possible.

Everytime you spam your main controls, and then use arrow keys, everything appears as a shit rating.
(but when you use your main controls, everything appears normally)

video:

https://user-images.githubusercontent.com/110793808/189508614-d2a7dcbc-38de-425f-8875-413669df74f2.mp4

---

**Comment by CrusherNotDrip** [comment]
I have already reported this issue #311

**Comment by YoshiCrafter29** [comment]
Fixed
