### ISSUE TITLE
The mod is not letting me into the game 

### ISSUE THREAD

**Issue by AlluringSnow495** [YoshiCrafter29/YoshiCrafterEngine#320]
So I don't know what happened but the mod doesn't let me actually go in the game I think what happened was I renamed the mod and it glitched it out and now when I try pressing enter on the title screen it does the thing it normally do when you press enter there but it never lets me into the game and I don't know how to fix can someone help?

**Comment by YoshiCrafter29** [comment]
switch to another mod
