### ISSUE TITLE
Bug Report: Updating to 2.3.0 from any version installs 2.1.0 and it breaks the game

### ISSUE THREAD

**Issue by ItsLJcool** [YoshiCrafter29/YoshiCrafterEngine#323]
## Which target are you using?
Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.2.0b, trying to go to 2.3.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
yes, just update the engine lmao

## Please describe your issue. Provide extensive detail and images if possible.
![Here ya go Yosh](https://user-images.githubusercontent.com/54383469/190029007-793df674-1a1c-4cd1-8465-9ca82c22ca1c.png)
also as you can see, the ModStates break after updating, **the current fix is just to install the EXE from the GitHub**

**Comment by YoshiCrafter29** [comment]
fixed
