### ISSUE TITLE
Noteskin Issue

### ISSUE THREAD

**Issue by ChumbleDev** [YoshiCrafter29/YoshiCrafterEngine#331]
## Which target are you using?
 i use windows - [me] Windows
- [ ] Mac
- [ ] Linux

## Please describe your issue. Provide extensive detail and images if possible.
--- Ok so i installed yoshi engine i got a note skin with a xml and put it in yoshi engine and opened the game and i clicked options then i went and opened the note skin up but it worked fine, except.... The colors were wrong and i didnt even change the colors at all they were set to normal and now im stuck with normal note assets this issue happend every time i installed a new noteskin besides the normal default noteskin could you help? Thanks for your time!

**Comment by YoshiCrafter29** [comment]
Not an issue.
![NOTE_assets_colored](https://user-images.githubusercontent.com/81191621/190425783-e89a10ef-d9c6-45c5-87e7-7a158d643c6c.png)
This is what the note assets looks like. Just make them red and it'll work fine.

**Comment by ChumbleDev** [comment]
Oh thanks i appreciate it!
