### ISSUE TITLE
Bug Report: Pixel dialogue boxes are broken

### ISSUE THREAD

**Issue by RosalinaFan573** [YoshiCrafter29/YoshiCrafterEngine#334]
## Which target are you using?
Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.3.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Play Week 6 in Story Mode
## Please describe your issue. Provide extensive detail and images if possible.
All Week 6 dialogue boxes create line breaks every time spaces are used in the dialogue's text file. It makes part of the dialogue unreadable and just looks ugly in general. I've tried everything I could to fix it and nothing worked.
![image](https://user-images.githubusercontent.com/15962490/190880336-e780d6ce-e54b-4b18-ab59-16de856c4623.png)

**Comment by YoshiCrafter29** [comment]
for the 3rd time, fixed
