### ISSUE TITLE
Help: source code

### ISSUE THREAD

**Issue by ulue** [YoshiCrafter29/YoshiCrafterEngine#335]
What I need help with is that whenever I try to lime test I get "Could not find haxelib "discord_rpc_yce", does it need to be installed?"
When I tried to download it said Error could not clone and I tried to do it a couple times but it didn't work
![bru](https://user-images.githubusercontent.com/84256344/190892857-3470ca4f-a25e-46e8-b626-f7c4750df5ac.png)

**Comment by YoshiCrafter29** [comment]
launch `config.bat`

**Comment by ulue** [comment]
> 

When I do it says error could not clone git
