### ISSUE TITLE
Bug Report: Character() does not support mod characters

### ISSUE THREAD

**Issue by Foxplort** [YoshiCrafter29/YoshiCrafterEngine#339]
## Which target are you using?
- [x] Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.3.2
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Use ***"Yoshi-Engine-code-samples/Haxe/Create a second Character.hx"***, ***"Yoshi-Engine-code-samples/Haxe/Change Character mid-song.hx"*** or another function to change/add characters (not only hx) with mod characters.
## Please describe your issue. Provide extensive detail and images if possible.
Engine try to take the sprite from the original fnf, and not from the mod you are using.
![image](https://user-images.githubusercontent.com/108976719/191091079-7ca8942f-926c-434c-9d7f-1a33bf39a5f3.png)
It doesn't work for lua either, but I haven't checked why

**Comment by SrtHero278** [comment]
the taking the sprite from og fnf is because the game tries finding your file in multiple libraries.
This should only happen if the game can't find your sprite.
Make sure you gave the correct file.
