### ISSUE TITLE
Enhancement: Adobe Animate Atlas Support

### ISSUE THREAD

**Issue by AbnormalPoof** [YoshiCrafter29/YoshiCrafterEngine#69]
## What is your suggestion, and why should it be implemented?
Basically allows users to input a spritemap.png and Animation.json/spritemap.json

NEEDED for some mods. (ex. bbpanzu's Doxxie mod)
Would make cutscenes MUCH more easier.

**Comment by itsDARK768** [comment]
this was going to be made but was scrapped, I am sorry but you may not have luck with this one

**Comment by YoshiCrafter29** [comment]
Added support from [this repo](https://github.com/Smokey555/Flixel-TextureAtlas).
