### ISSUE TITLE
Enhancement: New Tab In Toolbox 'Modcharts'

### ISSUE THREAD

**Issue by TonyTimee** [YoshiCrafter29/YoshiCrafterEngine#85]
## What is your suggestion, and why should it be implemented?
---
A New tab called modcharts.

Basicly you will create a modchart and it will ask 'Do you want to do notes or player'

Notes will be like wiggling and stuff

Player will be either bf, gf, or dad and can float up and down and stuff

This can be saved as either a .json file, .lua file or a .hx file.

Kade and / or Psych scripts can be supported with this as well

*hope yall understand it im bad at explaining*

**Comment by itsDARK768** [comment]
I understand this, this would be great to add in.

**Comment by YoshiCrafter29** [comment]
won't be added in

there's too much that can conflict with it, such as middlescroll, downscroll, gui size and such.

adding support for these would overcomplicate the ui, making it unusable.

also its better to code those in
