### ISSUE TITLE
can i work with you to make a mac port

### ISSUE THREAD

**Issue by BushsHaxs** [YoshiCrafter29/YoshiCrafterEngine#94]
it is cool if you don't want to i just want something to do

**Comment by BushsHaxs** [comment]
also this might be the last thing i try and work on before quiting

**Comment by YoshiCrafter29** [comment]
I'm sorry, but it won't be possible.
We don't know each other really, and i prefer to work alone for now.

Thanks for your help anyways. If you still want to contribute, make a fork and do everything mac related there.
